Feature/base template
wdfproje/wonderwp-base pull request #20
Opened 2019-03-08 11:35 UTC by marc-wdf

J'ai ajouté le template de base avec ce que l'on utilise habituellement et complété le template de page type.

2019-03-11 15:06 UTC, marc-wdf commented
J'ai supprimé les fichiers de langue de la PR

2019-03-13 14:14 UTC, jdm-web requested changes

2019-03-13 14:14 UTC, jeremy-wdf commented on web/app/languages/plugins/wwp-contact.pot
> +msgid ""
Il faut supprimer ce fichier.

2019-03-13 14:14 UTC, jeremy-wdf commented on web/app/themes/wwp_child_theme/assets/raw/scss/theme.scss
> +@import "header1";
Est-ce normal de retrouver header1 ici? Et pourquoi ce 1 d'ailleurs?

2019-03-13 14:14 UTC, jeremy-wdf commented on web/app/themes/wwp_child_theme/content-page.php
> +<?php
Ca n'a donc plus de sens de le garder dans le theme-core.
A virer dans le theme-core.

2019-03-13 14:48 UTC, marc-wdf commented
Je viens de corriger tous les points relevés. J'ai également supprimé le fichier content-page.php du Theme-Core

2019-03-13 17:53 UTC, jdm-web approved these changes

2019-03-13 17:53 UTC, merged