Feature/styleguide
wdfproje/wonderwp-base pull request #21
Opened 2019-03-11 09:02 UTC by marc-wdf

J'ai complété le styleguide

2019-03-11 14:58 UTC, marc-wdf commented
C'est bon, j'ai cleané la PR Styleguide, tu peux merge

2019-03-13 14:23 UTC, jdm-web requested changes

2019-03-13 14:23 UTC, jeremy-wdf commented on web/app/themes/wwp_child_theme/assets/raw/svg/facebook-white.svg
>  <?xml version="1.0" encoding="utf-8"?>
Est-ce qu'on est vraiment obligé d'avoir toutes ces variantes? On ne peut pas colorier les icônes en CSS plutôt?
avec une propriété `fill`?

2019-03-13 14:23 UTC, jeremy-wdf commented on web/app/themes/wwp_child_theme/plugins/wwp-espace-restreint/includes/ErThemeManager.php
> +<?php
A supprimer

2019-03-13 14:23 UTC, jeremy-wdf commented on web/app/themes/wwp_child_theme/styleguide/components/base/images.php
> +<!-- components/base/images.php -->
Est-ce que ça va vraiment être utile cette partie?
Quel usage tu avais en tête quand tu l'a rajoutée?

2019-03-13 14:23 UTC, jeremy-wdf commented on web/app/themes/wwp_child_theme/styleguide/components/molecules/download.php
> +<code>[wwpmodule slug='wwp-download' files='262,260']</code>
On ne devrait pas avoir en dur dans le styleguide, des parties correspondantes à des plugins. Je supprimerais donc cette section.

2019-03-13 14:23 UTC, jeremy-wdf commented on web/app/themes/wwp_child_theme/styleguide/components/molecules/download.php
> +<code>[wwpmodule slug='wwp-download' files='262,260']</code>
Par contre on pourrait brancher tous les plugins dans la page modèle au pire.
En plus on galèrerait pas à les trouver pour les tester comme ça.

2019-03-13 14:23 UTC, jeremy-wdf commented on web/app/themes/wwp_child_theme/styleguide/components/molecules/social_networks.php
> +</ul>
Il vaux largement mieux utiliser la version dynamique via le component. Pourquoi l'avoir refaite en statique?

2019-03-13 14:23 UTC, jeremy-wdf commented on web/app/themes/wwp_child_theme/styleguide/components/molecules/trombinoscope.php
> +<!-- components/molecules/trombinoscope.php -->
Non, pas de morceaux de plugins dans le styleguide.
Si tu as le plugin trombi dans un projet client, alors tu pourrais créer un composant front si tu veux changer de card, ça ok. Mais pas dans le styleguide par défaut.

2019-03-13 17:21 UTC, marc-wdf commented on web/app/themes/wwp_child_theme/assets/raw/svg/facebook-white.svg
>  <?xml version="1.0" encoding="utf-8"?>
Pour styliser un svg, il faut que celui-ci soit chargé dans le html; impossible dès lors que le svg est chargé en tant que background css. Il faudrait faire une règle dans le composant lui-même. Ce serait pas mal, plus compliqué à maintenir quand les logos sont modifiés…

2019-03-13 17:25 UTC, marc-wdf commented on web/app/themes/wwp_child_theme/styleguide/components/base/images.php
> +<!-- components/base/images.php -->
Cela permet de regrouper toutes les déclinaisons des tailles d'images (à la une, panoramique, standard…). Le PO, l'administrateur et le client ont ainsi les mêmes infos. intéressant quand le client se lance dans un recadrage industriel. Exemple pour CAHM.

2019-03-13 17:37 UTC, marc-wdf commented on web/app/themes/wwp_child_theme/styleguide/components/molecules/download.php
> +<code>[wwpmodule slug='wwp-download' files='262,260']</code>
Il me faut un lieu d'expression pour styler les composants avant le passage du dev. Le styleguide était pratique pour ça. Le modèle de page n'est pas adapté car représente plutôt un exemple de page de contenu très fourni. La page que tu as créée dans le socle "plugin listing" pourrait faire l'affaire. Par contre, si je dois créer un nouveau composant, je le créerai dans les molécules du styleguide.

2019-03-13 17:54 UTC, jeremy-wdf commented on web/app/themes/wwp_child_theme/styleguide/components/base/images.php
> +<!-- components/base/images.php -->
Dans ce cas il faut qu'on monte qqch en dynamique, pas en statique, ça n'aura aucune valeur sinon.

2019-03-13 17:58 UTC, jeremy-wdf commented on web/app/themes/wwp_child_theme/styleguide/components/molecules/download.php
> +<code>[wwpmodule slug='wwp-download' files='262,260']</code>
Ok pour une page listing des plugins.
Ok aussi pour créer une molécule dans le styleguide si tu en as besoin pour un projet donné.
Pas ok pour créer dans le styleguide du projet de référence des composants par avance concernant les plugins.

2019-03-13 17:59 UTC, jeremy-wdf commented
Il y a un conflit à adresser sur cette branche.
Pas grand chose, apparemment une histoire de taille d'excerpt.

2019-03-14 08:44 UTC, marc-wdf commented
J'ai géré le conflit. Il reste à régler la partie images du styleguide; je ne vois pas comment on peut la rendre dynamique, et je sais son utilité. Donc je suggère le merge.

2019-03-14 15:42 UTC, jdm-web approved these changes

2019-03-14 15:43 UTC, merged