Feature/styleguide
wdfproje/wonderwp-base pull request #25
Opened 2020-02-05 09:11 UTC by marc-wdf

J'ai renommé le composant Video en VideoEmbed. Ensuite j'ai ajouté un nouveau composant Video qui est basé sur des vidéos natives. Dans le styleguide les 2 blocks s'affichent correctement, cependant les vidéos ne se lancent plus lors du clic sur les triggers. Attention, il faut également rebrancher le composant VideoEmbed sur le plugin Video.

2020-02-10 15:35 UTC, marc-wdf commented
Jeremy j'ai terminé mes retours, je te laisse ajouter le toggle de classe sur le player natif

2020-02-11 14:27 UTC, marc-wdf commented
C'est bon de mon côté : j'ai ajouté des styles pour améliorer le rendu en fullscreen natif et re-créé la Card dans le styleguide.

2020-02-11 14:58 UTC, jdm-web requested changes

2020-02-11 14:58 UTC, jeremy-wdf commented on web/app/themes/wwp_child_theme/includes/Components/ProgressBar/ProgressBarComponent.php
> +<?php
Compare avec le composant progress bar de vinci qui est celui que j'ai le plus éprouvé en php.
J'avais aussi ajouté des transitions css sur la barre quand on change sa valeur.

2020-02-11 14:58 UTC, jeremy-wdf commented on web/app/themes/wwp_child_theme/includes/Components/ProgressBar/_progress-bar-component.scss
> +/*Barre de progression*/
Pareil, comparer avec Vinci.

2020-02-11 14:58 UTC, jeremy-wdf commented on web/app/themes/wwp_child_theme/includes/Components/Video/VideoComponent.php
> +use WonderWp\Plugin\GutenbergUtils\Bloc\Annotation\Block;
Il faudrait faire un essai de ne pas mettre de use en haut de page, puis de mettre le chemin complet dans l'annotation pour voir. 
Par exemple : 
```
/**
  * @var string
  * @WonderWp\Plugin\GutenbergUtils\Bloc\Annotation\BlockAttributes(component="PlainText",type="string",componentAttributes={"placeholder":"Titre"})
  */
```
Si jamais ça fonctionne alors ce serait cool, on pourrait laisser les annotations, et ça ne ferait pas d'erreur sur les projets sans gutenberg utils.

2020-02-11 14:58 UTC, jeremy-wdf commented on web/app/themes/wwp_child_theme/includes/Components/Video/VideoComponent.php
> +            <div class="video-player" id="' . $playerWrapId . '">
On dirait qu'on a 2 fois le mm Id. C'est pas bon du coup.

2020-02-11 14:58 UTC, jeremy-wdf commented on web/app/themes/wwp_child_theme/includes/Components/Video/_video-component.scss
> +  progress {
On aurait pas moyen de mutualiser avec le composant progress? 
Ca fait pas mal de code dupliqué.

2020-02-18 08:36 UTC, merged