Webpack differencial serving
wdfproje/wonderwp-base pull request #33
Opened 2021-08-12 15:28 UTC by Kevkehz

2021-08-16 09:51 UTC, jdm-web requested changes

2021-08-16 09:51 UTC, jdm-web commented on package.json
> -    "watch": "webpack --watch",
Peut-on garder les mêmes alias ?
(sauf start, on en a pas besoin)
Mais surtout la possibilité d'avoir d'un côté un builder et de l'autre un watcher.
C'est utile pour les commandes cli de pouvoir builder sans watcher.

2021-08-16 09:51 UTC, jdm-web commented on config/webpack/paths.js
> +  // #ATOMIC BUILD END
On s'est jamais servi de ça, autant le virer.

2021-08-16 09:51 UTC, jdm-web commented on config/webpack/paths.js
> +  "TweenMax": path.resolve('node_modules', 'gsap/src/uncompressed/TweenMax.js'),
```suggestion

```

2021-08-16 09:51 UTC, jdm-web commented on config/webpack/paths.js
> +  "TimelineMax": path.resolve('node_modules', 'gsap/src/uncompressed/TimelineMax.js'),
```suggestion

```

2021-08-16 09:51 UTC, jdm-web commented on config/webpack/paths.js
> +  //  "velocity": path.resolve('web', 'app/themes/wwp_child_theme/styleguide/atomic-core/js/velocity.js'), // Uncomment only for Atomic-Core build use
```suggestion

```

2021-08-16 09:51 UTC, jdm-web commented on config/webpack/webpack.base.config.js
> +  .enableIntegrityHashes(Encore.isProduction())
On ne s'en servira probablement pas.

2021-08-16 09:51 UTC, jdm-web commented on config/webpack/webpack.base.config.js
> +  .configureLoaderRule('sass', loaderRule => {
Ajouter en com le lien vers la doc.

2021-08-16 09:51 UTC, jdm-web commented on config/webpack/paths.js
> +  });
voir si on peut ajouter un fichier de polyfill en automatique si jamais on est en legacy.

2021-08-17 09:21 UTC, Kevkehz commented on config/webpack/paths.js
> +  });
done

2021-08-17 13:43 UTC, jdm-web commented on package.json
> +    "start": "encore dev --watch -c ./config/webpack/webpack.modern.config.js & encore dev --watch -c ./config/webpack/webpack.legacy.config.js",
C'est watch celui là du coup non ?

2021-08-17 13:43 UTC, jdm-web commented on package.json
> +    "@symfony/webpack-encore": "^1.5.0",
as-tu vérifié avec quelle version de node on pouvait faire tourner ça ?

2021-08-17 13:51 UTC, Kevkehz commented on package.json
> +    "start": "encore dev --watch -c ./config/webpack/webpack.modern.config.js & encore dev --watch -c ./config/webpack/webpack.legacy.config.js",
Oui c'est ça, j'ai modifié.

2021-08-17 13:58 UTC, Kevkehz commented on package.json
> +    "@symfony/webpack-encore": "^1.5.0",
Le build fonctionne en version node 10, 12 et 14

2021-08-17 14:03 UTC, jdm-web approved these changes
En attente des autres pour pouvoir merge.

2021-09-28 09:58 UTC, jdm-web requested changes

2021-09-28 09:58 UTC, jdm-web commented on Jenkinsfile
> +                    if(BRANCH_NAME=='master' || BRANCH_NAME=='develop'){
C'est surtout pour les sitemaps.
Vérifier qu'on ne les charge pas en prod.
Peut-être que ce test doit évoluer.

2021-09-28 09:58 UTC, jdm-web commented on config/webpack/paths.js
> +  "svg4everybody": path.resolve('node_modules', 'svg4everybody/dist/svg4everybody.min.js')
Essayer d'enlever l'alias, et de voir si svgforeverybody fonctionne toujours dans app_init.js

2021-09-28 09:58 UTC, jdm-web commented on config/webpack/webpack.base.config.js
> +  .enableVersioning(Encore.isProduction())
cf test jenkinsfile, à faire évoluer si besoin.

2021-09-28 14:24 UTC, jdm-web requested changes

2021-09-28 14:24 UTC, jdm-web commented on config/webpack/webpack.base.config.js
> +  .enableVersioning(Encore.isProduction() || process.env.NODE_ENV === 'production')
Activer tout le temps.

2021-09-28 14:24 UTC, jdm-web commented on package.json
> +    "build": "NODE_ENV=production encore dev --progress -c config/webpack/webpack.modern.config.js & encore dev --progress -c config/webpack/webpack.legacy.config.js & wait",
enlever le node_env

2021-09-28 15:45 UTC, jdm-web requested changes

2021-09-28 15:45 UTC, jdm-web commented on web/app/themes/wwp_child_theme/includes/Service/ThemeAssetService.php
> +    }
Je mettrais bien tout ça dans un asset manipulator enfant.
C'est le même contexte et la même idée que ce que nous avons discuté sur le thème parent en fait.

2021-09-29 06:54 UTC, Kevkehz commented on web/app/themes/wwp_child_theme/includes/Service/ThemeAssetService.php
> +    }
Je l'ai mis dans le `AssetManipulatorService` du thème versionné étant donné que cela ne devrait pas changer souvent.

2021-09-29 08:24 UTC, jdm-web approved these changes
OK, en attente des PRs sous jacentes pr composer update & merge.

2021-10-06 13:39 UTC, jdm-web requested changes
Il reste un gros composer update à faire j'ai l'impression, et on peut clôturer.

2021-10-06 13:39 UTC, jdm-web commented on composer.json
> +    "symfony/asset": "^5.3",
```suggestion

```

2021-10-07 07:20 UTC, merged