[Asset] optimize loading
wdfproje/wonderwp-base pull request #34
Opened 2021-10-07 13:47 UTC by Kevkehz

2021-10-07 14:50 UTC, jdm-web requested changes

2021-10-07 14:50 UTC, jdm-web commented on web/app/themes/wwp_child_theme/assets/raw/scss/critical.scss
> +@import "web/app/themes/wwp_child_theme/assets/fonts/fonts";
On ne peut pas garder ça.
On ne mettra que la police concernée.

2021-10-07 14:50 UTC, jdm-web commented on web/app/themes/wwp_child_theme/assets/raw/scss/theme.scss
> -@import "web/app/themes/wwp_child_theme/assets/fonts/fonts";
Il faut le remettre.

2021-10-07 17:02 UTC, jdm-web requested changes

2021-10-07 17:02 UTC, jdm-web commented on web/app/themes/wwp_child_theme/assets/raw/scss/critical.scss
> +@import "web/app/themes/wwp_child_theme/assets/fonts/fonts";
```suggestion
```

2021-10-11 08:47 UTC, jdm-web approved these changes

2021-11-02 08:32 UTC, Kevkehz commented
@jdm-web Cette PR est prête à être mergé.

2021-11-02 09:00 UTC, jdm-web requested changes

2021-11-02 09:00 UTC, jdm-web commented on Jenkinsfile
> +              if(BRANCH_NAME=='master'){
```suggestion
              if(BRANCH_NAME=='master' || BRANCH_NAME=='main'){
```

2021-11-02 09:00 UTC, jdm-web approved these changes

2021-11-02 09:01 UTC, merged